### ISSUE TITLE
Handling of the :host parameter doesn't seem to work properly.

### ISSUE THREAD

**Issue by mdorman** [DamienCassou/auth-password-store#1]
First, let me say I was very excited to see this package---my .authinfo.gpg file for gnus was the last thing I wasn't managing using password-store.

However, I seem to have run into a small incompatibility with gnus.

If I `(setq auth-source-debug 'trivia)`, and start gnus, it fails to login to my nnimap source.  The output from auth-source is:

    auth-source-search: found 4 backends matching (:max 1 :host ("servername") :port ("imap" "imap" "143") :user "username" :require (:user :secret) :create t)

If I then take that and plug it into `auth-source-search`, like so:

    (auth-source-search :max 1
                        :host '("servername")
                        :port '("imap" "imap" 143)
                        :user "username"
                        :require '(:user :secret)
                        :create t)

I do, in fact, get an error.  A partial backtrace is

    Debugger entered--Lisp error: (wrong-type-argument stringp nil)
      *** Internals of password-store elided***
      auth-pass--find-match(nil "username")
      auth-pass-search(:backend [object auth-source-backend "password-store" password-store "." t t t nil ignore auth-pass-search] :type password-store :require (:user :secret) :create nil :delete nil :max 1 :host ("servername") :port ("imap" "imap" 143) :user "username" :require (:user :secret) :create t)
      apply(auth-pass-search :backend [object auth-source-backend "password-store" password-store "." t t t nil ignore auth-pass-search] :type password-store :require (:user :secret) :create nil :delete nil (:max 1 :host ("servername") :port ("imap" "imap" 143) :user "username" :require (:user :secret) :create t))
      auth-source-search-backends(([object auth-source-backend "password-store" password-store "." t t t nil ignore auth-pass-search] [object auth-source-backend "~/.authinfo" netrc "~/.authinfo" t t t nil auth-source-netrc-create auth-source-netrc-search] [object auth-source-backend "~/.authinfo.gpg" netrc "~/.authinfo.gpg" t t t nil auth-source-netrc-create auth-source-netrc-search] [object auth-source-backend "~/.netrc" netrc "~/.netrc" t t t nil auth-source-netrc-create auth-source-netrc-search]) (:max 1 :host ("servername") :port ("imap" "imap" 143) :user "username" :require (:user :secret) :create t) 1 nil nil (:user :secret))
      auth-source-search(:max 1 :host ("servername") :port ("imap" "imap" 143) :user "username" :require (:user :secret) :create t)
      eval((auth-source-search :max 1 :host (quote ("servername")) :port (quote ("imap" "imap" 143)) :user "username" :require (quote (:user :secret)) :create t) nil)
      eval-last-sexp-1(nil)
      eval-last-sexp(nil)
      call-interactively(eval-last-sexp nil nil)
      command-execute(eval-last-sexp)

I believe the problem arises from the fact that the first parameter to `auth-pass--find-match` is `nil`---if you duplicate this by hand, you'll see the same `wrong-type-argument` error.

If, on the other hand, I change the call to `auth-source-search` to not pass a list for `:host`:

    (auth-source-search :max 1
                        :host "servername"
                        :port '("imap" "imap" 143)
                        :user "username"
                        :require '(:user :secret)
                        :create t)

everything seems to work:

    auth-source-search: found 1 CACHED results matching (:max 1 :host "servername" :port ("imap" "imap" 143) :user "username" :require (:user :secret) :create t)
    ((:host "servername" :port ("imap" "imap" 143) :user "username" :secret #[0 "ÁÂÀ\"" ["servername" auth-pass-get secret] 3 "

    (fn)"]))

So my belief is that the issue resides in `auth-pass-search`---I can see where it attempts to deal with coercing the host from a list ot a single item but it appears to fail.

I'm afraid I don't have any more time to do more diagnostics right now, but perhaps this evening I'll be able to actually instrument the code and figure out what's going on.  But I wanted to let you know about the issue, and record my research first.

**Comment by NicolasPetton** [comment]
Michael Alan Dorman <notifications@github.com> writes:

> First, let me say I was very excited to see this package---my
> .authinfo.gpg file for gnus was the last thing I wasn't managing using
> password-store.

Glad you like it!

> However, I seem to have run into a small incompatibility with gnus.

Thank you for reporting it, I will have a look.  It's very well
possible, as Damien and I use other MUA than Gnus.

**Comment by DamienCassou** [comment]
Thanks for letting us know. While you and @NicolasPetton are experimenting, I suggest setting `auth-source-do-cache` to `nil` to avoid having caching problems (and `pass` is so fast I decided to disable caching completely).

Maybe @tzz (author of `auth-sources`) can help you.

**Comment by tzz** [comment]
Sorry, I'm not sure what I can do to help? @DamienCassou it seems that the problem is only on the `auth-password-store` side?  Or is it something I can remedy on the `auth-source` side?

**Comment by mdorman** [comment]
I tend to agree that this is an `auth-password-store` thing to handle.  Thanks, though, Ted.

**Comment by NicolasPetton** [comment]
@mdorman Can you check if 3b4a1f9 fixed the issue for you?

**Comment by mdorman** [comment]
It would appear to be working fine.

**Comment by NicolasPetton** [comment]
Michael Alan Dorman <notifications@github.com> writes:

> It would appear to be working fine.

Cool.  Now we need a proper fix for handling several host names instead
of just taking the first non-nil one.

**Comment by DamienCassou** [comment]
@iquiw is working on #99
