### ISSUE TITLE
Format for Forge

### ISSUE THREAD

**Issue by leungbk** [DamienCassou/auth-password-store#102]
Related to #83. 

if I have

``` emacs-lisp
(setq auth-source-debug t)
(setq auth-source-do-cache nil)
```

and a file `~/.password-store/leungbk^forge@gitlab.com.gpg`, which is the same format as suggested in #83, with contents

```
TOKEN123
leungbk^forge
```

then when I try to `forge-pull` from a Gitlab repo I get in the `*Messages*` buffer

``` emacs-lisp
Error during redisplay: (jit-lock-function 1) signaled (invalid-function #<subr quote>) [3 times]
auth-source-password-store: searching for ’leungbk^forge@gitlab.com/api/v4’ in entry names (user: leungbk^forge)
auth-source-password-store: no match found
auth-source-password-store: searching for ’gitlab.com/api/v4’ in entry names (user: leungbk^forge)
auth-source-password-store: no match found
auth-source-search: found 1 results (max 1) matching (:host "gitlab.com/api/v4" :user "leungbk^forge" :max 1)
ghub--token: Required Gitlab token ("leungbk^forge" for "gitlab.com/api/v4") does not exist.
See https://magit.vc/manual/ghub/Support-for-Other-Forges.html for instructions.
```

I've also tried `~/.password-store/leungbk^forge@gitlab.com/api/v4.gpg`. I'd appreciate any suggestions on how to handle this.

**Comment by DamienCassou** [comment]
> `auth-source-password-store: searching for ’leungbk^forge@gitlab.com/api/v4’ in entry names (user: leungbk^forge)`

this is wrong. The path `/api/v4` shouldn't be part of the request, only hostnames should. Either you misconfigured forge or forge is buggy.

**Comment by iquiw** [comment]
The log looks written by old version before v4.0.0 (f4a51e78e76222ae68dba36185b0cb2f7ce166f2).

I could use forge with local GitLab using the latest `master`.

**Comment by leungbk** [comment]
> The log looks written by old version before v4.0.0 ([f4a51e7](https://github.com/DamienCassou/auth-password-store/commit/f4a51e78e76222ae68dba36185b0cb2f7ce166f2)).
> 
> I could use forge with local GitLab using the latest `master`.

Thanks, just tried again with the latest `auth-password-store` upstream and it works. Sorry, should have done that first instead of assuming the Emacs-bundled version was up to date.
