### ISSUE TITLE
gpg-agent high cpu spike during auth-password-store lookup

### ISSUE THREAD

**Issue by divansantana** [DamienCassou/auth-password-store#11]
Hi,

Firstly, I find this package a huge help to me and I'm sure to others. It's really awesome - so thanks a lot.

I'm new to Emacs and I've got this to work nicely though I notice a bug or issue perhaps with my configuration.

When I attempt a login into a service from emacs, the auth lookup queries my password store, during this time, Emacs freezes for quite a few seconds(10+) and my CPU shows gpg-agent using 90 something cpu %. 

A specific example:

Using mediawiki extension accessing a site https://wiki.mywiki.co.za

I have this file in place already:

```
.password-store/wiki.mywiki.co.za.gpg
```

With content similar to below
```
PasswordOnLineOne
user:myusername
port:443
```

I see the elow process:
```
gpg-agent --homedir /home/example/.gnupg --use-standard-socket --daemon
```

use 90 something % of CPU for a while

I also see various processes like this in the ps tree.
```
gpg2 -d --quiet --yes --compress-algo=none --no-encrypt-to --batch --use-agent /home/example/.password-store/dyn.com.gpg
```

and 
```
gpg2 -d --quiet --yes --compress-algo=none --no-encrypt-to --batch --use-agent /home/example/.password-store/creditexpert.co.za.gpg
```

Perhaps what's causing the brief emacs hang and CPU spike is because auth-password-store is scanning many pass entires instead of going directly to the correct one?

Is my configuration wrong, is there something I can do better.

If you need more info, please let me know how I can debug it so can offer a better bug report.

PS using auth-password-store from stable melpa.

**Comment by DamienCassou** [comment]
I confirm `auth-password-store` is sometimes very slow. What do you have in your `*Messages*` buffer (accessible with `C-h e`) regarding `auth-password-store`? Le code important est sur https://github.com/DamienCassou/auth-password-store/blob/master/auth-password-store.el#L130.

**Comment by divansantana** [comment]
Nothing useful in `*Messages*` it seems
```
Posting to: https://wiki.mywiki.co.za/mediawiki/api.php
Contacting host: wiki.mywiki.co.za:443
Posting to: https://wiki.mywiki.co.za/mediawiki/api.php [2 times]
```

To me it looks like auth-password-store decrypts each and every pass listed in the password store in reverse order from z-a before selecting the appropriate entry which is causing it to be slow and hang.

Would be better if it decrypted just the appropriate entries, based on destination hostname.

**Comment by DamienCassou** [comment]
Please evaluate `(setq auth-source-debug t)` and check the `*Messages*` buffer again

**Comment by divansantana** [comment]
Ah
```
auth-password-store: searching for 'https://wiki.mywiki.co.za/mediawiki/' in entry names
auth-password-store: no entry name matched 'https://wiki.mywiki.co.za/mediawiki/', looking inside entries
auth-source-search: found 0 results (max 1) matching (:max 1 :host "https://wiki.mywiki.co.za/mediawiki/" :port "https")
auth-password-store: searching for 'wiki.mywiki.co.za' in entry names
auth-source-search: found 1 results (max 1) matching (:max 1 :host "wiki.mywiki.co.za" :port "https")
Posting to: https://wiki.mywiki.co.za/mediawiki/api.php
Contacting host: wiki.mywiki.co.za:443
Posting to: https://wiki.mywiki.co.za/mediawiki/api.php
Posting to: https://wiki.mywiki.co.za/mediawiki/api.php
```
My entry is called `wiki.mywiki.co.za.gpg`. It seems to want it to be called `https://wiki.mywiki.co.za/mediawiki/.gpg` which I think is not possible due to the `/` in the name.

**Comment by DamienCassou** [comment]
I have the same problem with some Emacs extensions. I thought about 2 potential solutions but didn't try them:

1. add a new element to `auth-source' and improve `auth-password-store` to let users specify different password-store directories that way: `(setq auth-sources '((password-store "~/.password-store/emacs") (password-store "~/.password-store"))`. In `~/.password-store/emacs`, you put the minimal amount of passwords to make the special Emacs extensions work. The rest of your passwords go to `~/.password-store`. The idea is that Emacs will first try to search for passwords inside the `emacs/` subdirectory which should go fast because the directory is small.

2. change the Emacs extensions so that they ask search for a host without its protocol: e.g., `"wiki.mywiki.co.za"` instead of `"https://wiki.mywiki.co.za/mediawiki"`.

**Comment by divansantana** [comment]
Those sound like workable options.

What about an option

3. `auth-password-store` does a check and strips any invalid hosts like `https://wiki.mywiki.co.za/mediawiki` and corrects it to `wiki.mywiki.co.za` before doing the lookup?

That way would require a fix in mutliple emacs extensions (mediawiki, ERC etc)

**Comment by DamienCassou** [comment]
I guess you meant *would not require a fix*. I agree that your solution is by far the simplest. Even though you are *new to Emacs*, do you still want to try to implement it yourself?

**Comment by divansantana** [comment]
Yes I meant "would not require a fix" - thanks.
I am new to Emacs and not much of a dev but let me see if I can try make time in the next week or so to give this a shot.

**Comment by DamienCassou** [comment]
Please check that this patch fixes your problem.

**Comment by divansantana** [comment]
Tested and verified. Works great. Very nice!

Thanks a lot.

**Comment by DamienCassou** [comment]
Great. I'm releasing a new version then.
