### ISSUE TITLE
merge with/into auth-source?

### ISSUE THREAD

**Issue by tzz** [DamienCassou/auth-password-store#24]
Hi! I'd really like auth-source.el to support `pass` out of the box (no external dependencies). So your package as it is now doesn't work exactly that way, users need to go out and get it, and the docs don't mention anything about `pass`.

Should I write a new method for auth-source.el, copy yours into auth-source.el, or do you want to merge this code into Emacs? Then the docs would be adjusted accordingly.

Or is there another way? What do you think?

**Comment by NicolasPetton** [comment]
Ted Zlatanov <notifications@github.com> writes:

Hi Ted,

> Should I write a new method for auth-source.el, copy yours into
> auth-source.el, or do you want to merge this code into Emacs? Then the
> docs would be adjusted accordingly.

I don't know if you remember, but some time ago we talked about this
package and the idea of making auth-source extensible.

We never did it though, but that's something I'd really like to have.

That said, there would be nothing wrong with integrating this code with
auth-source itself.

Nico

**Comment by DamienCassou** [comment]
Like @NicolasPetton, I believe it's more important to have a tiny module system within auth-sources so that everyone can plug their backend.

That being said, I'm also ok integrating pass inside auth-source. Here are some notes regarding this potential integration:

- dependency: the code has a small dependency over password-store.el which should probably be removed before integration (that shouldn't be hard)
- contributor: there have been 5 contributors beyond @NicolasPetton and me. One of them (@foudfou) contributed a significant portion of code
- tests: if auth-password-store is to be integrated, it's extensive test suite should be too

**Comment by tzz** [comment]
You're already using the module system--it's the `auth-source-backends` list. What's missing? Do you want `auth-sources` entries to be easier for pass? Sorry I can't find the original discussion about auth-source modules, but I'm more than happy to continue it here or in the original list, and to implement what's needed to help you. Long-term I can see more of these modules popping up, so I will gladly implement your suggestions to make it easier. But yours is a special case because `pass` is a GNU project and IMO a great cross-platform option.

The equivalent of password-store.el will have to be implemented internally, yes. That's partly what I meant about external dependencies. We can work on that after we agree on the import method.

I have to leave the contributor agreement to you. But if needed, we can rewrite the code, keeping the same ideas; I don't think that's ethically wrong since this package is already under GPL v3. That applies to the tests as well. Ultimately my goal is not to take this code necessarily but to give the users an easy way out of the box in Emacs to use `pass`, without external dependencies.

**Comment by NicolasPetton** [comment]
Ted,

I don't remember the details anymore, but IIRC, `auth-source` has limitations with extensibility, and we had to use an advise here:

https://github.com/DamienCassou/auth-password-store/blob/master/auth-password-store.el#L86

**Comment by NicolasPetton** [comment]
From our email discussion:

  The problem we faced was that `auth-source-backend-parse' uses a `cond'
  form, thus we couldn't extend it cleanly.  Or maybe we missed something?

   Maybe a `auth-source-handlers' alist would be sufficient.  It could
   simply be in a `cond' format, so `auth-source-backend-parse' becomes

     (auth-source-backend-parse-parameters entry `(cond ,@auth-source-handlers))

   or whatever the macro equivalent is. Then packages would simply add to
   that alist. Or we can simplify that whole `auth-source-backend-parse'
   function to make it more extendable.  How would you want it to work?

**Comment by DamienCassou** [comment]
> You're already using the module system--it's the auth-source-backends list. What's missing?

I would prefer to have a registration mechanism beyond the advice:

```emacs
(advice-add 'auth-source-backend-parse :before-until #'auth-pass-backend-parse)
```

> `pass` is a GNU project 

I didn't know that. Where do you see that?

> I want to specifically bring it into the Emacs core

ok

> I have to leave the contributor agreement to you

ok. I will contact the contributor(s)

> But if needed, we can rewrite the code [...]. My goal is not to take this code necessarily

I would prefer the code to be adapted and not rewritten as I spent time making it good (for my taste).

**Comment by tzz** [comment]
Oops, sorry, I meant "GPL project" but my fingers typed "GNU." I've edited the comment, thanks.

I can definitely add a registration mechanism for the parser. It will probably be a list of functions that get called sequentially by `auth-source-backend-parse` before the current code (and we may refactor that code) so you'd just prepend to the list from the external package. That's cleaner than a `cond` macro on an alist, I think.

So if we do that, we could bring your code in a separate file next to `auth-source.el`; bring in some version of your tests in the Emacs tests, and require it from the auth-source code. That may be a good chance to factor out the MacOS keychain and the rest as well from the main library into small separate files.

When you're ready, we can just branch off under emacs.git `feature/auth-source-pass` and collaborate there.

Thanks for your patience and I'm glad we can work on this.

**Comment by NicolasPetton** [comment]
Ted Zlatanov <notifications@github.com> writes:

> I can definitely add a registration mechanism for the parser. It will
> probably be a list of functions that get called sequentially by
> `auth-source-backend-parse` before the current code (and we may
> refactor that code) so you'd just prepend to the list from the
> external package. That's cleaner than a `cond` macro on an alist, I
> think.

I agree, although it was you who actually proposed this solution :-P

> When you're ready, we can just branch off under emacs.git
> `feature/auth-source-pass` and collaborate there.

Unfortunately, Damien doesn't have write access to the Emacs repo.
@DamienCassou, can you ask Eli or John if they could give you commit
access?

**Comment by DamienCassou** [comment]
> we can just branch off under emacs.git feature/auth-source-pass and collaborate there

ready when you are

> @DamienCassou, can you ask Eli or John if they could give you commit access?

/cc @jwiegley: would you mind getting me access to the Emacs repo so I can collaborate with @tzz and @NicolasPetton on integrating `auth-password-store` inside Emacs?

**Comment by tzz** [comment]
All right, I've started work in the branch `feature/auth-source-pass` with some cleanups.

**Comment by tzz** [comment]
The branch code and tests should now support adding more sources backend parsers easily. Take a look. Thanks.

**Comment by DamienCassou** [comment]
Should we discuss implementation details here? Here is some feedback:

```emacs
(defvar auth-source-backend-parser-functions nil)
````

If `add-hook` should be used; I would have suffixed the variable name with `hook` such as `auth-source-parse-hook`. 

Regarding the documentation, I propose something like:

```diff
 
 (defvar auth-source-backend-parser-functions nil
-  "List of auth-source parser functions
-These functions return backends from an entry in `auth-sources'.
-Add your backends to this list with `add-hook'.")
+  "List of auth-source parser functions.
+Each function takes an entry from `auth-sources' as parameter and
+returns a backend or nil if the entry is not supported.  Add a
+parser function to this list with `add-hook'.  Searching for a
+backend starts with the first element on the list and stops as
+soon as a function returns non-nil.")
 
 (defun auth-source-backend-parse (entry)
-  "Creates an auth-source-backend from an ENTRY in `auth-sources'."
+  "Create an auth-source-backend from an ENTRY in `auth-sources'."
```

**Comment by DamienCassou** [comment]
Without commit access, I started working on https://github.com/DamienCassou/emacs/pull/1. You have write access.

**Comment by tzz** [comment]
@DamienCassou I'll comment in the PR, we can close this one I think, unless you want to keep it open until the final merge.
