### ISSUE TITLE
Getting assignment forms before submission into Emacs

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/auth-password-store#25]
@mineo @foudfou @NicolasPetton 

To everyone who has contributed to auth-password-store: @tzz (maintainer of `auth-sources`) would like to include
auth-password-store in the next version of Emacs, but to do so, I need copyright
assignment forms to be signed by anyone who has contributed to auth-password-store. If
you do not wish to sign such a copyright assignment form, let me know so that
I can find a way to back out any changes you have made.

Thank you!

Context: #24

**Comment by DamienCassou** [comment]
(this call is adapted from https://github.com/jwiegley/use-package/issues/282)

**Comment by NicolasPetton** [comment]
@mineo @foudfou please send an email to assign@gnu.org, they will give you the form to sign.

**Comment by mineo** [comment]
https://github.com/jwiegley/use-package/issues/282#issuecomment-158254504 mentions that documentation changes don't need copyright assignment forms. My only contributions are two commits in `README.md`, do I still need to sign the forms? If yes, I'd be happy to, but if there's an easier way for me, I'd be equally happy to not get involved with paperwork ;-)

**Comment by DamienCassou** [comment]
@mineo I have no idea and understand you very well :-).

**Comment by foudfou** [comment]
Assignment complete.

**Comment by DamienCassou** [comment]
Thank you very much.

**Comment by mineo** [comment]
Whoops, I totally forgot this. I've now at least sent an email to assign@.

**Comment by DamienCassou** [comment]
Thank you both.

**Comment by tzz** [comment]
This means we have all the assignments? Wonderful! Thanks!
