### ISSUE TITLE
default documented value for host not handled properly

### ISSUE THREAD

**Issue by jellelicht** [DamienCassou/auth-password-store#29]
Currently, this package does not really like having `nil` and/or `t` passed as the host argument.
I get:
```
split-string: Wrong type argument: stringp, nil
```
when not passing in any `:host` argument to `auth-source-search`. From `auth-source-search`'s documentation:
```
:host (X Y Z) means to match only hosts X, Y, or Z according to
the match rules above.  Defaults to t.
```
This documentation is actually not entirely correct; looking at the netrc backend of `auth-source-search`, they seem to rebind `:host` to `t` in the backend, which imho seems like a silly place if supposedly `auth-source-search` gives this guarantee. 

Either way, would the correct behaviour for auth-password-store in this case not be to match *all* pass files, and filter based on other arguments such as `:max`, `:port` and `:user`? I understand that right now, `:host` maps more or less directly onto the filename in the password store, so this might require some changes to the underlying logic.

**Comment by jellelicht** [comment]
It also seems that the `:max` arguments is ignored. Should I open a separate ticket for this?

**Comment by DamienCassou** [comment]
@tzz up

**Comment by tzz** [comment]
Sorry, I was away and couldn't reply sooner.

@DamienCassou is there a default file or directory we can scan?

@jellelicht can you please provide a full example that we can use, right now it's not clear how you called it exactly. Thank you!

**Comment by DamienCassou** [comment]
Ted Zlatanov <notifications@github.com> writes:
> @DamienCassou is there a default file or directory we can scan? 

there is no default file, but the code I wrote always checks 
~/.password-store. I have to admit the auth-sources API is still 
obscure to me. I would be happy to implement a solution, if I know 
what is expected. 

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jellelicht** [comment]
I will try to come up with a more self-contained example, somewhere today. 


The most important part is that when leaving `:host` `nil`, auth-password-store matches zero instances, whereas the documentation/other backends insinuate that it should be treated like more of a wildcard in that specific case.

**Comment by DamienCassou** [comment]
Any news?

**Comment by jellelicht** [comment]
```;; With in ~/.password-store/irc.rizon.net:
; <mypw>
; host: irc.rizon.net
; user: jlicht
; port: nickserv

;; With in ~/.password-store/personal/irc.rizon.net:
; <mypw>
; host: irc.rizon.net
; user: jlicht-other
; port: nickserv

(use-package auth-password-store
  :ensure t
  :init
  (auth-pass-enable))

;; This works:
(auth-source-search :host "irc.rizon.net")
;; => ((:host "irc.rizon.net" :port "nickserv" :user "jlicht" :secret #[<mypassword stuff>]))

;; This works:
(auth-source-search :host "irc.rizon.net" :user "jlicht-other")
;; => ((:host "irc.rizon.net" :port "nickserv" :user "jlicht-other" :secret #[<mypassword stuff>]))

;; This does not:
(auth-source-search :host "irc.rizon.net" :max 2)
;; => ((:host "irc.rizon.net" :port "nickserv" :user "jlicht" :secret #[<mypassword stuff>]))

;; I would expect, after reading the docs for `auth-source-search', that both of
;; my password-store entries should be matched

;; This also does not work: ()
(auth-source-search) ;; should match anything
;; => split-string: Wrong type argument: stringp, nil

;; According to the `auth-source-search' docs, :host should be t by default,
;; which does not happen

;; This also does not work:
(auth-source-search :host t) ;; should match the "first" match, any url
;; => auth-pass--find-match: Wrong type argument: char-or-string-p, t

;; So we see that even with `:host' bound to t, there are still issues.
```

**Comment by jellelicht** [comment]
Sorry for the delay, life happened. 
I tried to make it as self-contained as possible.
If anything is still unclear, please do ping me.

**Comment by DamienCassou** [comment]
@jellelicht thanks for the detailed report.

@tzz can you please confirm @jellelicht expresses the expected behavior? Should I implement it like that?

**Comment by jellelicht** [comment]
Is there still something I can help with regarding this issue?
My elisp-fu is not really up to snuff to do the actual work, sadly, but testing and/or verifying stuff is something I could do.

**Comment by DamienCassou** [comment]
@tzz up?

**Comment by tzz** [comment]
@DamienCassou @jellelicht I'm sorry it's taking so long. I'm traveling and have had zero time to work on this. I feel terrible.

I'll try to fix this as soon as I'm back next week. If you want to speed up my work, you could prepare test cases; see `emacs.git/test/lisp/auto-source*.el` for the format.

**Comment by DamienCassou** [comment]
@tzz: I'm not sure there is a bug in auth-source. Maybe it is in auth-source-pass, maybe there is no bug. In fact, I would like you to tell me what is the expected behavior. Then, I can work on the code if you want to.

**Comment by jellelicht** [comment]
The example I posted above shows behaviour which is inconsistent with my interpretation of the (also posted) documentation of `auth-source-search`. 

This implies one of three things:

- The documentation of `auth-source-search` is incorrect, and needs an update
- The current implementation of auth-password-store needs to be brought in-line with the `auth-source-search` spec
- My understanding of the documentation of `auth-source-search` is incorrect; (although a small rewrite to clarify might still be appreciated).

So I think the important thing right now is to define what the correct behaviour of auth-source + auth-password-store _should_ be, and then change the code and/or documentation to reflect this behaviour.

**Comment by tzz** [comment]
I'm working on writing tests and improving the docs. But I can confirm that the **intended** behavior of any `auth-source` backend is:

* `:host t` should match anything, returning at most one entry (since `:max` defaults to 1)
* `:host t :max 2` should match anything, returning two entries
* `:host X :max 2` should match up to 2 entries that have host `X`

If any backend, including the netrc backend, doesn't work as described, it needs to be fixed. But the best way to ensure that is with tests, so I've started writing some. Feel free to add your own.

I'll try to push my changes this weekend, if time allows. Thanks for your patience.

**Comment by tzz** [comment]
Hi! I've added tests to show clearly the expected auth-source behavior with the `netrc` backend. I hope these tests are helpful in settling the questions about the auth-password-store behavior. I hope that helps resolve this issue.

```
commit 3565437bf27373fe053d93dbb0c295f221834b07
Author: Ted Zlatanov <tzz@lifelogs.com>

    Add auth-source tests and codify its API better
```

**Comment by DamienCassou** [comment]
Ted Zlatanov <notifications@github.com> writes:
> ```
> commit 3565437bf27373fe053d93dbb0c295f221834b07
> Author: Ted Zlatanov <tzz@lifelogs.com>
>
>     Add auth-source tests and codify its API better
> ```


Thanks for this. Would it be possible that backends are tested with
exactly the same test? I would like to write something like that to be
sure auth-source-pass follows the guidelines:

    (ert-deftest auth-source-pass-implements-auth-source ()
      (let ((...prepare the store...))
        (auth-source-test-backend-api #'auth-source-pass-backend-parse)))


The ...prepare the store... part would setup the password store so that
it contains exactly what is expected, e.g., what is now in
auth-source-test-searches:

    '("machine a1 port a2 user a3 password a4"
      "machine b1 port b2 user b3 password b4"
      "machine c1 port c2 user c3 password c4"))

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tzz** [comment]
Agreed! Good plan, and easy to implement.

I'm not sure what the equivalent `pass` layout would be, unfortunately. If you tell me, then it's simply making a temporary directory, populating it, and cleaning it up at the end, and I can do all that.

**Comment by DamienCassou** [comment]
Ted Zlatanov <notifications@github.com> writes:
> Agreed! Good plan, and easy to implement.
>
> I'm not sure what the equivalent `pass` layout would be,
> unfortunately. If you tell me, then it's simply making a temporary
> directory, populating it, and cleaning it up at the end, and I can do
> all that.

No need for a temporary directory, the test macro
auth-source-pass--with-store emulates that. Look at the unit tests for
examples. You might want to write something like that (untested):

    (ert-deftest auth-source-pass-implements-auth-source ()
      (auth-source-pass--with-store '(
        ("a1" ("port" . "a2") ("user" . "a3") ("secret" . "a4"))
        ("b1" ("port" . "b2") ("user" . "b3") ("secret" . "b4"))
        ("c1" ("port" . "c2") ("user" . "c3") ("secret" . "c4")))
          (auth-source-test-backend-api #'auth-source-pass-backend-parse)))

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tzz** [comment]
@DamienCassou in theory you're right, but I'm concerned that the real-world behavior of `pass` differs from the theoretical one implemented by that macro. Why not use the real thing? Are you concerned about performance, side effects, or test environment requirements?

**Comment by DamienCassou** [comment]
Ted Zlatanov <notifications@github.com> writes:
> @DamienCassou in theory you're right, but I'm concerned that the
> real-world behavior of `pass` differs from the theoretical one
> implemented by that macro. Why not use the real thing? Are you
> concerned about performance, side effects, or test environment
> requirements?

I don't understand your concern. The whole implementation of
auth-source-pass is tested like that because it is much simpler to
simulate a password store than to create many encrypted files and
directories. Moreover, auth-source-pass does not depend on the pass
command-line utility.

That being said, if you still prefer to use a real file system, I don't
see any strong objection to do that. It would be easier to use
assess-filesystem them, but I'm not sure if it has already been
integrated in Emacs or not.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jellelicht** [comment]
@tzz If real world behaviour of `pass` differs from the theoretical one implemented by the macro, then surely that would be a bug in the implementation of either. I guess it depends on what you want to do, something more akin to a unit test vs an actual end-to-end test. Either works for me.

**Comment by tzz** [comment]
My concern is that we're testing pure data, not how `pass` behaves. So it's more of a unit test and I was thinking of an integration test as @jellelicht said.

But I understand it's easier and not a big concern, so I'm OK with it, you've answered my question.

**Comment by jellelicht** [comment]
A gentle bump, have there been any developments regarding this issue?

**Comment by DamienCassou** [comment]
Jelle Licht <notifications@github.com> writes:
> A gentle bump, have there been any developments regarding this issue?

I've started looking at it too. Sorry for the delay. May I ask you how
it affects you in particular?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jellelicht** [comment]
I'd like to use `auth-password-store` as a drop-in replacement for `.authinfo.gpg`. 
Several configuration layers of Spacemacs use `auth-source-search` for finding the relevant login info. [This](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bchat/rcirc/funcs.el#L15) is a good example of what Spacemacs expects to be able to do with auth-source backends.

Specifically, I want to store my smtp and irc passwords in password-store only, instead of the current situation where passwords are stored in both password-store and authinfo.gpg.

**Comment by DamienCassou** [comment]
Jelle Licht <notifications@github.com> writes:
> Specifically, I want to store my smtp and irc passwords in
> password-store only, instead of the current situation where passwords
> are stored in both password-store and authinfo.gpg.

I don't use spacemacs, but I use password-store for everything
(including smtp, irc, slack, …). I don't have any authinfo file anymore.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jellelicht** [comment]
In the linked code fragment, the following is done to search for passwords:

```
(auth-source-search :port '("nickserv" "bitlbee" "quakenet")
                                 :require '(:port :user :secret))
```

Which should work according to documentation:
`:host (X Y Z) means to match only hosts X, Y, or Z according to
the match rules above.  Defaults to t.`

As auth-password-store currently does not support leaving `:host` empty or even setting it to `t` without crashing, this does not currently work, forcing me to put some (redundant) info in the authinfo file.

**Comment by DamienCassou** [comment]
I know that I have to work, don't worry :-). I'm just saying that you can probably work-around the issue in the meantime if you want to remove your authinfo file rapidly. For example, you can use `auth-pass-get` directly from your init.el file. Look at mine for example: https://github.com/DamienCassou/emacs.d.

**Comment by DamienCassou** [comment]
@jellelicht I implemented this https://github.com/DamienCassou/auth-password-store/pull/33. I'm not sure password store can reasonably implement a requirement like:

```
(auth-source-search :port '("nickserv" "bitlbee" "quakenet")
                                 :require '(:port :user :secret))
```

as it would mean opening every gpg file in the password store, one after the other to find the one defining the right port/protocol. This would be really slow (I tried that in the past and this was impossible to use for me and a user who reported the problem).

What I do instead, but which is not compatible with the code above, is to use hosts instead. I have a "freenode.net" entry in my password store and [circe](https://github.com/jorgenschaefer/circe) as my IRC client. Then, I have this in my init.el

```emacs
(defun my/get-password (host &optional user)
      "Return password for HOST and USER."
      (when-let ((entry (auth-pass--find-match host user)))
        (auth-pass-get 'secret entry)))
(setq-default circe-sasl-password #'my/get-password)
(setq-default circe-nickserv-password #'my/get-password)
```

**Comment by DamienCassou** [comment]
Another way would be to name your entries with a trailing colon and port/protocol name. Something like "freenode.net:nickserv.gpg". What do you think?

**Comment by jellelicht** [comment]
@DamienCassou I decided to apply a patch akin to your `my/get-password` from above to my emacs configuration, so for now all practical issues are resolved. The problem (choice?) of not being able to match `:host` to `t` remains though, making auth-password-store an incomplete backend.

For now, perhaps auth-password-store should at least gracefully handle the fact that as a backend for `auth-source-search`, it can receive a `:host` wildcard? E.g. log a warning and pass the query on to the next backend. Right now, it crashes with the `split-string: Wrong type argument: stringp, nil` error, which I hope we can all agree on is definitely not the correct behaviour.

**Comment by jellelicht** [comment]
Regarding your proposal to add port/protocols to the filenames: I would dislike this very much, but only for the superficial reason that I really like short and clear filenames for my password database :smile:.

**Comment by jellelicht** [comment]
@DamienCassou would you be okay with accepting a PR that basically makes auth-password-store do the following when receiving a `host` equal to `t`:
- Show a warning message along the lines of "Auth-password-store currently cannot handle wildcards"

Subsequently, or when receiving a `host` equal to `nil`:
- Return 0 matches without crashing, potentially allowing other registered `auth-source-search` backends to try and find the secret matching the query.

The advantage here is that auth-password-store will never break existing workflows, while still allowing auth-password-store to be used in the arguably more efficient way you described earlier instead of the brute-force approach #33. To me, it seems a reasonable compromise.

**Comment by DamienCassou** [comment]
Please go ahead.

**Comment by jellelicht** [comment]
I've put up a (very simple) PR. If I missed something, I'll try to address it somewhere this week still.

**Comment by DamienCassou** [comment]
I propose we close this issue. Thanks for mitigating it with your PR.

**Comment by DamienCassou** [comment]
Feel free to reopen if you plan on doing something about it.
