### ISSUE TITLE
auth-password is not enabled

### ISSUE THREAD

**Issue by ReichKV** [DamienCassou/auth-password-store#32]
Back to https://github.com/DamienCassou/auth-password-store/issues/31

Sorry, I still cannot initialize the package. I tried:
```elisp
(use-package auth-source
  :init
  (progn
    (setq auth-source-debug t)
    (setq auth-source-do-cache nil)))

(use-package auth-password-store
  :after auth-source
  :init
  (progn
    (setq auth-sources '(password-store))))
```

from your config and also:

```elisp
(use-package auth-password-store :ensure t :init (auth-pass-enable) )
```

and
```elisp
(use-package auth-password-store :demand t :config (auth-pass-enable) )
```
and just lines from the documentation
```elisp
(require 'auth-password-store)
(auth-pass-enable)
```

Nothing works. The package doesnot start when i load emacs. If i use one of these methods manually, it works

**Comment by ReichKV** [comment]
Ok, now i figure out it. I also defined "auth-sources" variable

**Comment by DamienCassou** [comment]
Good :-).
