### ISSUE TITLE
auth-source-search SPEC does not handle custom tokens.

### ISSUE THREAD

**Issue by jellelicht** [DamienCassou/auth-password-store#35]
From the `auth-source-search` documentation, as a part of `SPEC`, the search query;
```
:K (V1 V2 V3) for any other key K will match values V1, V2, or
V3 (note the match rules above).
```
and: 
```
:require (A B C) means that only results that contain those
tokens will be returned.  Thus for instance requiring :secret
will ensure that any results will actually have a :secret
property.
```

As I understand this, this means that I should be able to filter on custom properties, as well as make sure that these custom properties are included in the query results. AFAIK auth-password-store currently ignores any tokens but `:host :port :user :secret`.

**Comment by DamienCassou** [comment]
I confirm this is a bug.

**Comment by DamienCassou** [comment]
I don't have any plan to make auth-source-pass handle the whole requirements of auth-source. This is a lot of work and doesn't always make sense or is feasible with pass. I think I will, at least for some time, only handle actual use cases. 

I'm closing the issue. Feel free to reopen it if needed.
