### ISSUE TITLE
Advice to handle two users for the same domain

### ISSUE THREAD

**Issue by marcowahl** [DamienCassou/auth-password-store#45]
Hello!

Thanks for pass!

Could you give a hint how to store passwords for two users for the same domain, please.  E.g. hans@mail.org and gretel@mail.org.

With the current suggestion to use a further line for the user this is impossible AFAICS.

Thanks,

**Comment by DamienCassou** [comment]
On November 17, 2017 11:40:12 PM GMT+01:00, Marco Wahl <notifications@github.com> wrote:
> Could you give a hint how to store passwords for two users for the same
>domain, please.  E.g. hans@mail.org and gretel@mail.org.

Can you please try the latest version of the package and 2 files within the same directory? E.g., mail.org/hans.gpg and mail.org/gretel.gpg.
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by marcowahl** [comment]
Looks good to me, thanks.
