### ISSUE TITLE
usage examples for mu4e and erc

### ISSUE THREAD

**Issue by dni** [DamienCassou/auth-password-store#46]
hi guys!

im trying to use your awesome plugin, but i cant get it working at all.
i use spacemacs and added your package to additional packages and set  user config

`  
(require 'auth-password-store)
  (auth-pass-enable)
`

but it doesnt seem to do anything :(

in my m4ue i use smtp-send-it and i always get authentification failed, cant really figure out my problem, :( any ideas on how to debug?

in my pass i have.

`
├── smtp.mail.eu-west-1.awsapps.com
│   ├── office@dnilabs.com

secret
host: smtp.mail.eu-west-1.awsapps.com
user: office@dnilabs.com
port: 465
`
same with irc.freenode.org for ERC no success

what am i missing? i dont really get it, maybe the package isnt installed correctly? how to verify?
or did i get something wrong?

any help appreciated, thanks!

**Comment by DamienCassou** [comment]
Can you please add this to your config so we can debug more easily?

```emacs
(setq auth-source-debug t)
(setq auth-source-do-cache nil)
```

Try again and watch the `*Messages*` buffer.

> in my m4ue i use smtp-send-it

I use the same in notmuch, we should manage to fix your issue :-).

**Comment by dni** [comment]
Hi! Thank you for your help!

Hm, looks like it found something... 

```
Sending via mail...
auth-password-store: searching for ’smtp.mail.eu-west-1.awsapps.com:465’ in entry names (user: nil)
auth-password-store: no match found
auth-password-store: searching for ’smtp.mail.eu-west-1.awsapps.com’ in entry names (user: nil)
auth-password-store: no match found
auth-source-search: found 1 results (max 1) matching (:host "smtp.mail.eu-west-1.awsapps.com" :port "465" :user nil :max 1 :require nil :create nil)
auth-password-store: searching for ’smtp.mail.eu-west-1.awsapps.com:465’ in entry names (user: nil)
auth-password-store: no match found
auth-password-store: searching for ’smtp.mail.eu-west-1.awsapps.com’ in entry names (user: nil)
auth-password-store: no match found
auth-source-search: found 1 results (max 1) matching (:host "smtp.mail.eu-west-1.awsapps.com" :port "465" :user nil :max 1 :require (:user :secret) :create t)
smtpmail-send-it: Sending failed: 530 5.7.0  Authentication required

```

**Comment by DamienCassou** [comment]
Can you please:

1. tell me if you have a `auth-pass--find-match-unambiguous` function in auth-password-store.el. If you don't, please update auth-password-store to its latest version;
2. what happens if you replace `smtp.mail.eu-west-1.awsapps.com/office@dnilabs.com.gpg` with `smtp.mail.eu-west-1.awsapps.com.gpg` with a `user: office@dnilabs.com` line inside.

Sorry for your problem.

**Comment by dni** [comment]
you dont have to excuse ;) i have to thank you for providing this functions.
JJk
1. its there
2. it works now 💃 

nice, so do i have any way of adding multipe user like this?
i have 2 or more users at ´smtp.mail.eu-west-1.awsapps.com´

**Comment by DamienCassou** [comment]
> nice, so do i have any way of adding multipe user like this?

no. This was just a way for me to understand the problem better. You have to go back to the directory approach. Can you please give me your smtp-send-it configuration?

Also, please tell me more about your IRC setup: emacs configuration, password store organization, *Messages* buffer.

**Comment by dni** [comment]
Hi!

```elisp
  (setq message-send-mail-function 'smtpmail-send-it)
  (setq mu4e-account-alist
    '(("dnilabs"
        (user-full-name "dnilabs e.U")
        (user-mail-address "office@dnilabs.com")
        (smtpmail-auth-credentials '(("smtp.mail.eu-west-1.awsapps.com" 465 "office@dnilabs.com" nil)))
        (smtpmail-default-smtp-server "smtp.mail.eu-west-1.awsapps.com")
        (smtpmail-smtp-server "smtp.mail.eu-west-1.awsapps.com")
        (smtpmail-stream-type ssl)
        (smtpmail-smtp-service 465)
       )
      ("hostinghelden"
       (user-mail-address "office@hostinghelden.at")
       (user-full-name "Hostinghelden GmbH")
       (smtpmail-auth-credentials '(("smtp.mail.eu-west-1.awsapps.com" 465 "office@hostinghelden.at" nil)))
       (smtpmail-default-smtp-server "smtp.mail.eu-west-1.awsapps.com")
       (smtpmail-smtp-server "smtp.mail.eu-west-1.awsapps.com")
       (smtpmail-stream-type ssl)
       (smtpmail-smtp-service 465)
       )
)
```
im now using the plaintext pw approach for erc password ;), here i dont really care that much.

**Comment by DamienCassou** [comment]
When I was using ERC (now using [Circe](https://github.com/jorgenschaefer/circe)), I had this:

```emacs
(defun my/irc-freenode ()
  (interactive)
  (erc :server "irc.freenode.net"
       :password (password-store-get "freenode.net")))))
```

**Comment by dni** [comment]
should i do the same for `smtpmail-auth-credentials` ? :D

**Comment by DamienCassou** [comment]
The variable `smtpmail-auth-credentials` has been removed in Emacs 24.1. Which version of Emacs are you using? Could you try switching to `smtpmail-smtp-user`?

I think I reproduced your setup and it works for me. The lines of interest in my configuration are at https://github.com/DamienCassou/emacs.d/blob/master/init.el#L650. My password store now contains a file `choca.pics/damien@cassou.me.gpg`. Things are working fine.

**Comment by dni** [comment]
nice i changed it, like you said, had some trouble, getting it to work again with some accounts, both with user: office, but with different hosts. didnt work, so i just changed to user: to office@xy.com and it worked.

thank you for your time 👍

**Comment by komali2** [comment]
> The variable `smtpmail-auth-credentials` has been removed in Emacs 24.1. Which version of Emacs are you using? Could you try switching to `smtpmail-smtp-user`?
> 
> I think I reproduced your setup and it works for me. The lines of interest in my configuration are at https://github.com/DamienCassou/emacs.d/blob/master/init.el#L650. My password store now contains a file `choca.pics/damien@cassou.me.gpg`. Things are working fine.

This entire conversation was very helpful, but as you can imagine your init.el has changed quite a bit in the last 3  years ;P Any chance you still have how that config looked?

**Comment by DamienCassou** [comment]
Here are the relevant variable/value pairs:

```
             (profile-maildir . "/Perso")
             (notmuch-fcc-dirs . "Perso/Sent")
             (user-mail-address . "damien@cassou.me")
             (message-signature . t)
             (smtpmail-queue-dir . "~/Mail/Perso/queued-mail/")
             (smtpmail-local-domain . nil)
             (smtpmail-smtp-user . "damien@cassou.me")
             (smtpmail-smtp-server . "choca.pics")
             (smtpmail-stream-type . ssl)
             (smtpmail-smtp-service . 465)
```

Please open a new issue if you struggle configuring something. I suggest you first set

```emacs
(setq auth-source-debug t)
(setq auth-source-do-cache nil)
```

Then run `M-x auth-source-forget-all-cached`, then do whatever you need and finally check the `*Messages*` buffer.
