### ISSUE TITLE
Decrypting /path/to/file.gpg every time?

### ISSUE THREAD

**Issue by dieggsy** [DamienCassou/auth-password-store#48]
With `.authinfo.gpg`, I could run e.g. "sudo pacman -Syu" in eshell and i'd only get a message about decrypting `.authinfo.gpg` once, presumably because the connection was still open (or the password cached, or both?). 

With `auth-password-store`, if I keep a file `localhost.gpg`, I get the `Decrypting ...` message every time I issue a command that requires root. I'm not exactly sure why this happens, but it would seem more work than necessary is being done in the second example.

**Comment by DamienCassou** [comment]
>  get the Decrypting ... message every time I issue a command that requires root

auth-password-store indirectly asks password-store (the bash script) to read files which ultimately uses gpg to decrypt files from the filesytem. Emacs is not responsible for decryption. I don't understand why you get this `Decrypting...` message.

If you are using Emacs 26, are you sure you use auth-password-store and not auth-source-pass (which is a rewrite of auth-password-store for inclusion in Emacs itself)?

If you are sure you use auth-password-store, can you please show me your `auth-sources` variable?

**Comment by dieggsy** [comment]
@DamienCassou Ah, I am using `auth-source-pass`... the Readme is a little unclear about this, I thought it was the same.

**Comment by DamienCassou** [comment]
diego <notifications@github.com> writes:
> @DamienCassou Ah, I am using `auth-source-pass`... the Readme is a
> little unclear about this, I thought it was the same.

would you mind trying to improve the README please?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by dieggsy** [comment]
Sure, though isn't the described behavior still suboptimal for `auth-source-pass`? Even if emacs is responsible for dercyption (as with `.authinfo.gpg`) it doesn't seem like it should be decrypting on every command or action that requires root. I'm not really sure how this is handled by emacs or `auth-source` normally, but I'd think it'd be nicer to be closer to the "normal" `auth-source` behavior.

**Comment by DamienCassou** [comment]
> Sure, though isn't the described behavior still suboptimal for auth-source-pass?

I guess it depends what kind of "optimal" we are talking about. Reading the file from disk and decrypting it each time the same entry is read certainly costs a little time. But what about security? Would you like all your password-store entries to be available all the time in RAM? I'm ok to pay the cost of decrypting the file for each use of the entry if it increases my security. Moreover, opening and decrypting a password-store entry is so fast that it never slows down my Emacs. Do you experience slowness or are you only annoyed by the "Decrypting..." message in the echo area?

**Comment by dieggsy** [comment]
@DamienCassou I'm not noticing slowness and see your point about security. I'm just comparing `auth-source-pass`'s behaviour to `auth-source`'s, and wondering how useful it actually is to decrypt every time, given that it may be unnecessary if there is an open tramp connection. 

That is, it is more secure to decrypt every time, but since in the described use case it would _already_ be possible to execute the root command (due to tramp), there is no point in decrypting again. Sure, the cost is minor, but it doesn't feel like it should be happening in the first place. I'm not actually sure how `auth-source` handles this, since there's no mention of tramp anywhere in it, or if it's just some default emacs/tramp behavior that `auth-source-pass` somehow overrides?

**Comment by dieggsy** [comment]
@DamienCassou I think I understand the source of my issue and can clarify now - `auth-source` uses `password-cache`, `auth-source-pass` does not. I believe `auth-source` makes this optional with the variable `auth-source-do-cache`. It would be nice if `auth-source-pass` had this option as well, for consistency with `auth-source`, and to give the user the option.

(At least, I think this is the root of the issue, I could be wrong)

**Comment by dieggsy** [comment]
Sorry to spam a bit, after turning off `password-cache`, and noticing similar behavior in `auth-source` I'm not convinced this was the reason after all - it may still be something to do with tramp. In any case, I think it's worth further investigation even if as a user option.

**Comment by tzz** [comment]
@DamienCassou I think the backend should decide if and how to cache. `auth-source-do-cache` is advisory and doesn't have to be considered.

Regarding auth-source in core, I think the current caching behavior of the netrc backend is a decent compromise, but could certainly be improved. I've argued that relying on an external binary like GnuPG to do all encryption and decryption is a security risk as well. Calling it repeatedly is slow in many cases (older machines, old platforms, remote operation, etc.) so I hope you agree it's OK to leave the decision to the backend.

**Comment by dieggsy** [comment]
@tzz even if i set `auth-source-do-cache` to `nil`, `.authinfo.gpg` isn't decrypted every time a command requires root access (i'm testing from eshell) - or at least, I don't get the `Decrypting ...` message. Do you know why this is? I sort of jumped around in the above comments thinking it might be a tramp thing, or a cache thing, but I'm not really sure.

**Comment by tzz** [comment]
I looked at the source. It's been a while, and I should have checked before speaking earlier.

* @DamienCassou I see that `auth-source-do-cache` provides no way for the backend to override it, because it's consulted before the backend gets checked. Sorry for my incorrect statement earlier. I was thinking of the netrc caching. I can add a way for the backend to request no caching, if you'd like.

* @dieggsy inspect `password-data`, looking for keys in the form `(auth-source . ANYTHING)` (see `auth-source-forget-all-cached` for an example). Is your query cached? It shouldn't be, if you've set `auth-source-do-cache` but please check.

* Everyone: the netrc backend has a **separate** cache on top of the general query cache. That's probably what's preventing the decryption. And that cache can't be disabled, it's just a defvar that always gets checked. I can make it respect `auth-source-do-cache`, is that good enough? Or should we have a more fine-grained control per backend? I'm OK with either approach.

**Comment by dieggsy** [comment]
@tzz  @DamienCassou  I still think caching should be optional - I'd like to have caching with `auth-source-pass` (once I understand what's actually happening with `auth-source`, I guess) 

With `auth-source-do-cache` set to `nil`, `(auth-source . ANYTHING)` is not present in `password-data`, as you say. It only shows up if `auth-source-do-cache` is `t`.  However, something is still preventing decryption as you say.

**Comment by dieggsy** [comment]
To clarify my previous statement, I think `auth-source-pass` is somehow already overriding caching, since it's causing decryption every time. It'd be nice if it only optionally did this.

**Comment by DamienCassou** [comment]
My opinion is that:

- auth-source should be responsible for asking the right backend, and potentially caching the result
- each backend should be responsible for properly answering queries from auth-source

**Comment by dieggsy** [comment]
@DamienCassou I might understand the behavior I was describing a bit better. I think the `Decrypting...` message is probably a result of using `insert-file-contents` in `auth-source-pass--read-entry`. I guess `insert-file-contents` uses `epa` internally on encrypted files, so it may be that this behavior is "expected" given the implementation.

**Comment by DamienCassou** [comment]
I'm closing this issue as there is nothing I plan to do about it for now. Feel free to reopen if you have any plan to work on it or if there is an idea you would like me to try.
