### ISSUE TITLE
async-smtpmail-send-it silently fails

### ISSUE THREAD

**Issue by seanfarley** [DamienCassou/auth-password-store#50]
Trying to follow the advice given in other issues but no debug messages appear (I'm guessing due to the async nature).

Basically, `async-smtpmail-send-it' does not work (tested with both emacs 25 [melpa package] and 26 [internal auth source]). I can try to help debug but ran into a roadblock as I described here:

https://github.com/jwiegley/emacs-async/issues/53

Any guidance is much appreciated!

**Comment by DamienCassou** [comment]
Hi @seanfarley,

I know nothing about the async package. I guess it starts a new Emacs instance which needs to know about auth-password-store. There is an `async-smtpmail-before-send-hook` variable where you could add a function configuring auth-password-store.

/cc @jwiegley

**Comment by seanfarley** [comment]
Sigh. I swear tried that before but apparently I did not (at least not correctly). You are right that enabling pass in the hook does work. Exact code in case anyone is curious:

```lisp
(add-hook 'async-smtpmail-before-send-hook #'auth-source-pass-enable)
```
