### ISSUE TITLE
Clarify “service” in Readme.md

### ISSUE THREAD

**Issue by akater** [DamienCassou/auth-password-store#51]
Readme.md says:

> If you use several services in the same host, you can add a colon and the service name at the end of the filename: e.g., `host:service.gpg`.

What is a service? An example, or multiple examples, would help a lot.

Neither `man pass` nor “data organization” page Readme.md links to, do not mention “services”, or examples of files with colon in their names.

**Comment by DamienCassou** [comment]
What do you think about the fix at #52?

**Comment by DamienCassou** [comment]
Done.
