### ISSUE TITLE
Obsolete name arg "password-store" to constructor auth-source-backend

### ISSUE THREAD

**Issue by jabranham** [DamienCassou/auth-password-store#54]
I get this warning when byte compiling `auth-password-store` on Emacs 26:

```
auth-password-store.el:82:1:Warning: Obsolete name arg "password-store" to
    constructor auth-source-backend
```

And the variable definition looks weird too:

```
auth-source-backend’s value is ‘auth-source-backend’

  This variable is obsolete since 25.1;
  use \='auth-source-backend instead

Documentation:
Not documented as a variable.
```

Any idea how to fix this?

**Comment by DamienCassou** [comment]
I've seen this as well but tried to pretend I didn't :-). Now, I can't anymore. Any clue @tzz?

**Comment by tzz** [comment]
I've never seen this either, and the error makes no sense. Emacs byte compilation is black magic to me.

**Comment by jabranham** [comment]
Do you want me to email emacs-devel and see if anyone has an idea what this could mean?

**Comment by DamienCassou** [comment]
Alex Branham <notifications@github.com> writes:
> Do you want me to email emacs-devel and see if anyone has an idea what
> this could mean?

sure.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jabranham** [comment]
@DamienCassou @tzz 

I got some help from emacs-devel. Looks like the name argument is just unused and can be removed. https://lists.gnu.org/archive/html/emacs-devel/2018-02/msg00342.html

So changing the defvar to 

```elisp
(defvar auth-pass-backend
  (auth-source-backend ;; "password-store"
   :source "." ;; not used
   :type 'password-store
   :search-function #'auth-pass-search)
  "Auth-source backend for password-store.")
```

solves the issue for me.

**Comment by DamienCassou** [comment]
On February 12, 2018 6:19:37 PM GMT+01:00, Alex Branham <notifications@github.com> wrote:
>```elisp
>(defvar auth-pass-backend
>  (auth-source-backend ;; "password-store"
>   :source "." ;; not used
>   :type 'password-store
>   :search-function #'auth-pass-search)
>  "Auth-source backend for password-store.")
>```
>
>solves the issue for me.

Would you mind opening a PR?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jabranham** [comment]
Done, #56
