### ISSUE TITLE
Entries with paths are not resolved

### ISSUE THREAD

**Issue by tadfisher** [DamienCassou/auth-password-store#61]
Example pass entry:

`host.example.com/path/v3/username.gpg`

I expect the result of `(auth-source-pass--find-match "host.example.com/path/v3" "username")` to match this entry.

However, `auth-source-pass--find-all-by-entry-name` checks that the full `entryname` (in this case, `"host.example.com/path/v3"`) is a member of the entry's path *after* splitting its path components:

```emacs-lisp
(member entryname (split-string entry "/"))))
```

which expands to

```emacs-lisp
(member "host.example.com/path/v3" '("host.example.com" "path" "v3" "username"))
```

I believe the comparison could be made against the entire path component minus the final component without impacting existing functionality:

```emacs-lisp
(defun auth-source-pass--find-all-by-entry-name (entryname user)
  "Search the store for all entries either matching ENTRYNAME/USER or ENTRYNAME.
Only return valid entries as of `auth-source-pass--entry-valid-p'."
  (seq-filter (lambda (entry)
                (and
                 (or
                  (let* ((components (split-string entry "/"))
                         (components-host-user
                          (member entryname (cons (string-join (butlast components) "/") (last components)))))
                    (and (= (length components-host-user) 2)
                         (string-equal user (cadr components-host-user))))
                  (string-equal entryname (file-name-nondirectory entry)))
                 (auth-source-pass--entry-valid-p entry)))
              (auth-source-pass-entries)))
```

**Comment by DamienCassou** [comment]
As far as I can see, this breaks the tests `auth-source-pass-make-divansantana-happy`. Could you please open a PR making your change work with existing tests and adding a new one?

**Comment by DamienCassou** [comment]
I forgot to say I was sorry for the late reply.

**Comment by DamienCassou** [comment]
Any news?

**Comment by tadfisher** [comment]
Hi, I'll take a look at creating a PR. Thanks for the reminder.

**Comment by DamienCassou** [comment]
I'm closing the issue for now. Please reopen when you work on it.
