### ISSUE TITLE
Help with ERC

### ISSUE THREAD

**Issue by leungbk** [DamienCassou/auth-password-store#72]
I've been having trouble using this to log into ERC.

The relevant parts of my config are as follows:

``` emacs-lisp
(use-package auth-source
  :defer t)

(use-package auth-source-pass
  :after (auth-source)
  :init
  (setq auth-sources '(password-store)))

(use-package password-store
  :commands (password-store-get)
  :config
  (setq password-store-password-length 16))

(setq auth-source-debug t)
(setq auth-source-do-cache nil)

(setq erc-autojoin-channels-alist '(("freenode.net")))
(setq erc-nick "leungbk")

(defun my/irc-freenode ()
    (interactive)
    (erc :server "irc.freenode.net"
         :password (password-store-get "freenode.net")))
```

And my password file (`~/.password-store/freenode.net/leungbk:6667.gpg`) is
```
~mypassword~
user: leungbk
```

Even with the debugging settings on, there don't seem to be any useful messages in the `*Messages*` buffer:

```
Connecting to irc.freenode.net:6667... 
Logging in as `leungbk'...
Logging in as ‘leungbk’... done
```

In the ERC buffer, I see

```
21:12 *** leungbk has changed mode for leungbk to +Ri
21:12 -NickServ- This nickname is registered. Please choose a different
          nickname, or identify via /msg NickServ identify <password>.
21:12 -NickServ- Invalid password for leungbk.
21:12 -freenode-connect- Due to the persistent ongoing spam, all new
          connections are being set +R (block messages from unidentified
          users) and will be scanned for vulnerabilities. This will not harm
          your computer, and vulnerable hosts will be notified.
```

Here's what I get in `ielm`:

``` emacs-lisp
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (password-store--run-show "freenode.net")
"freenode.net\n└── leungbk:6667"
ELISP> (s-lines (password-store--run-show "freenode.net"))
("freenode.net" "└── leungbk:6667")

ELISP> (password-store--run "show"
                       "freenode.net")
"freenode.net\n└── leungbk:6667"
ELISP> 
```

I've tried copy/pasting my password from my file and can log in that way, so I know that the password in my file is correct.

I'd appreciate any help. Thanks for your time.

**Comment by DamienCassou** [comment]
Brian Leung <notifications@github.com> writes:
> I've been having trouble using this to log into ERC.

have you solved your problem? How?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by leungbk** [comment]
Thanks for your response. I solved the issue by removing the port from the file name and making sure the directories lined up. `~/.password-store/freenode.net/leungbk.gpg` should get called with `(erc-tls :server "irc.freenode.net" :port 6697
             :password (password-store-get "freenode.net/leungbk"))`

**Comment by creichert** [comment]
@leungbk I believe if you rename your `freenode.net/leungtbk` to `irc.freenode.net/leungbk`, it will "just work". Here is my config:


    (use-package auth-source-pass
      :ensure t
      :config
      (auth-source-pass-enable))
    (use-package erc
      :commands (erc)
      :init
      (setq
       erc-user-full-name "creichert"
       ;;; ... other configs
       )
      :config
      (erc-tls :server "irc.freenode.net" :port 6667 :nick "creichert"))

> -NickServ- This nickname is registered. Please choose a different nickname, or
>            identify via /msg NickServ identify <password>.
> -freenode-connect- Due to the persistent ongoing spam, all new connections are
>                  being set +R (block messages from unidentified users) and
>                  will be scanned for vulnerabilities. This will not harm your
>                  computer, and vulnerable hosts will be notified.
> -NickServ- You are now identified for creichert.


I hope this helps, maybe I'm misunderstanding?

**Comment by creichert** [comment]
My understanding is you don't need the additiona `password-store-*` calls because erc uses `auth-sources`. Even then, auth-source-pass has built-ins like [`auth-source-pass-get`)[https://github.com/DamienCassou/auth-password-store/blob/3de8bbb51054f495f0363a3121f287b15e0d9049/auth-source-pass.el#L100)

**Comment by leungbk** [comment]
Thanks! I wasn't sure how to get everything working without that extra function.
