### ISSUE TITLE
Using gitlab and ghub

### ISSUE THREAD

**Issue by jabranham** [DamienCassou/auth-password-store#83]
I'm wondering if anyone has had success getting ghub to work with gitlab. I've got two gitlab tokens I need in my password store (my password + the API access token). ghub needs `(auth-source-search :host "gitlab.com/api/v4")` to return the API entry. Note that it can't rely on `:user` since it uses entries like `username^packagename` (in other words, I'd have to add a new entry for each repo on gitlab).

I've tried having in ~/.password-store:

```
gitlab.com/api/v4.gpg # API key
gitlab.com/api/v4/username.gpg # API key
gitlab.com/username.gpg # has my login info
```

but no success.

**Comment by DamienCassou** [comment]
Would you mind turning on `auth-source-debug` and off `auth-source-do-cache` then copy/paste here the messages of the `*Messages*` buffer?

**Comment by jabranham** [comment]
Sure thing: 

With it saved as `gitlab.com/api/v4.gpg` or `gitlab.com/api/v4/username.gpg`, then `(auth-source-search :host "gitlab.com/api/v4")` results in:

```
auth-source-pass: searching for ’gitlab.com:443’ in entry names (user: nil)
auth-source-pass: no match found
auth-source-pass: searching for ’gitlab.com’ in entry names (user: nil)
auth-source-pass: no match found
auth-source-search: found 1 results (max 1) matching (:host "gitlab.com/api/v4")
(nil)
```

This is using auth-source-pass version `4.0.1` (the latest in Emacs git master)

**Comment by DamienCassou** [comment]
Alex Branham <notifications@github.com> writes:
> With it saved as `gitlab.com/api/v4.gpg` or `gitlab.com/api/v4/username.gpg`, then `(auth-source-search :host "gitlab.com/api/v4")` results in:

thank you. I'm more interested into the messages that appear when ghub
can't find any password store entry.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jabranham** [comment]
Here ya go:

```
auth-source-pass: searching for ’jabranham^forge@gitlab.com:443’ in entry names (user: jabranham^forge)
auth-source-pass: no match found
auth-source-pass: searching for ’jabranham^forge@gitlab.com’ in entry names (user: jabranham^forge)
auth-source-pass: no match found
auth-source-pass: searching for ’gitlab.com:443’ in entry names (user: nil)
auth-source-pass: no match found
auth-source-pass: searching for ’gitlab.com’ in entry names (user: jabranham^forge)
auth-source-pass: no match found
auth-source-search: found 1 results (max 1) matching (:host "gitlab.com/api/v4" :user "jabranham^forge" :max 1)
ghub--token: Required Gitlab token ("jabranham^forge" for "gitlab.com/api/v4") does not exist.
```

I thought making a file `gitlab.com/api/v4/jabranham^forge.gpg` would solve the issue but it doesn't seem to.

**Comment by DamienCassou** [comment]
Alex Branham <notifications@github.com> writes:
> auth-source-pass: searching for ’jabranham^forge@gitlab.com:443’ in entry names (user: jabranham^forge)

I guess that ’jabranham^forge@gitlab.com.gpg’ would work. If that's not
acceptable to you, would you mind trying
https://github.com/DamienCassou/auth-password-store/pull/80?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jabranham** [comment]
Thanks, using `jabranham^forge@gitlab.com.gpg` does indeed work. I'll test out that PR later when I get a chance.

**Comment by iquiw** [comment]
I am trying to solve the same problem.

`user^forge@host.gpg` works, but it seems to try to decrypt the file for each access to GitLab. (`auth-source-do-cache` is `t`)

**Comment by DamienCassou** [comment]
> it seems to try to decrypt the file for each access to GitLab

if auth-password-store is called multiple times even when `auth-source-do-cache` is `t`, then there is probably a bug outside of this package.

**Comment by iquiw** [comment]
> if auth-password-store is called multiple times even when auth-source-do-cache is t, then there is probably a bug outside of this package.

I see. I will check again.

**Comment by iquiw** [comment]
I set `debug-on-message` to `"Decrypting ~ .gpg...done"`, then the BackTrace in reverse order is

1. `ghub--auth`
2. `ghub--token`
3. `auth-source-pass-get`
4. `auth-source-pass-parse-entry`
5. `auth-source-pass--read-entry`

`ghub--token` seems to call `auth-source-pass-get` [here](https://github.com/magit/ghub/blob/c7ca6780bcd4d00d22e668e74b25f865ba892a45/ghub.el#L821).

**Comment by DamienCassou** [comment]
@iquiw I understand now, thank you for the investigation. When `auth-source-do-cache` is t, auth-source correctly caches the result of the search for a matching entry. The entry itself doesn't contain the password, but [a function to retrieve the password](https://github.com/DamienCassou/auth-password-store/blob/master/auth-source-pass.el#L79). The password must then be decrypted by executing the function, this is the purpose of the [code you found](https://github.com/magit/ghub/blob/c7ca6780bcd4d00d22e668e74b25f865ba892a45/ghub.el#L821). This is why the password is decrypted each time `ghub--token` is called. If you think that this is a problem, please open a new issue.

I'm closing this issue now because I think the original issue was solved.

**Comment by iquiw** [comment]
@DamienCassou Thanks. I suppose #81 will fix my issue (not tried yet).
