### ISSUE TITLE
Feature Request: Support alternate separator character between host and port

### ISSUE THREAD

**Issue by iquiw** [DamienCassou/auth-password-store#86]
I'm using password-store (actually [gopass](https://www.gopass.pw/)) on Windows as well as on Unix.

Windows does not allow filename to contain colon (`:`), so it would be nice if `auth-source-pass` can use alternate character (e.g. `#`?) as separator between host and port.

**Comment by DamienCassou** [comment]
Iku Iwasa <notifications@github.com> writes:
> Windows does not allow filename to contain colon (`:`), so it would be
> nice if `auth-source-pass` can use alternate character (e.g. `#`?) as
> separator between host and port.


I'm ok with that. Are you willing to send me a PR please?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by iquiw** [comment]
> I'm ok with that. Are you willing to send me a PR please?

Which is preferable?

(a) Support both `:` and `#`
(b) Add customizable variable to specify separator char

**Comment by DamienCassou** [comment]
Iku Iwasa <notifications@github.com> writes:
>> I'm ok with that. Are you willing to send me a PR please?
> (a) Support both `:` and `#`
> (b) Add customizable variable to specify separator char

I would prefer (b) with a note on the README.

Thank you

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
