### ISSUE TITLE
Support $PASSWORD_STORE_DIR environment variable

### ISSUE THREAD

**Issue by ajgrf** [DamienCassou/auth-password-store#97]
Upstream pass supports overriding the default password store directory by setting the `$PASSWORD_STORE_DIR` environment variable. It would be nice if the default value of `auth-source-pass-filename` automatically used this variable when it's set.

**Comment by DamienCassou** [comment]
Alex Griffin <notifications@github.com> writes:
> Upstream pass supports overriding the default password store directory
> by setting the `$PASSWORD_STORE_DIR` environment variable. It would be
> nice if the default value of `auth-source-pass-filename` automatically
> used this variable when it's set.


indeed, good idea. Do you care enough to send a PR?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
Ping
